# Generated by Django 3.2.8 on 2024-08-16 09:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatInterestUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Rejected'), (2, 'Accepted')])),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='int_acp_usr1', to=settings.AUTH_USER_MODEL)),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='int_acp_usr2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
