# Generated by Django 3.2.8 on 2024-08-16 09:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatinterestuser',
            name='user1',
        ),
        migrations.RemoveField(
            model_name='chatinterestuser',
            name='user2',
        ),
        migrations.AddField(
            model_name='chatinterestuser',
            name='opt_user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='int_opt_user', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chatinterestuser',
            name='raised_user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='int_raised_user', to='auth.user'),
            preserve_default=False,
        ),
    ]
