# Generated by Django 3.2.8 on 2024-08-16 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chatinterestuser_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatinterestuser',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Rejected'), (2, 'Accepted'), (3, 'Raised')]),
        ),
    ]
