# Generated by Django 3.2.8 on 2024-08-17 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_chatinterestuser_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatinterestuser',
            name='message',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
